name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: RUSTFLAGS="-C target-feature=+aes" cargo build --verbose
    - name: Generates test.iso
      run: | 
        sudo apt install cryptsetup
        dd if=/dev/zero bs=1M count=20 > tests/test.iso
        echo -n "password" | cryptsetup luksFormat --pbkdf-force-iterations=4 --pbkdf-memory=32 tests/test.iso -d -
    - name: Run tests
      run: cargo test --verbose
